# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HrVMfzuvlg7RyBj8urA1fKvFON7RdHEd
"""

class Student :
  def __init__(self,name,English,Math):
    self.name = name
    self.English = English
    self.Math = Math

  def score_ave(self):
    ave = (self.English + self.Math)/2
    return ave
Nakamura = Student("nakamura",76,81)
Tanaka = Student("tanaka",92,80)
Suzuki = Student("suzuki",50,79)
Students = [Nakamura, Tanaka, Suzuki]

for a in Students:
  print(a.name,"の平均点は",a.score_ave(),"です")